### PR TITLE
Added cli-service feature 'vue config'

### PR DESCRIPTION
**Pull request by beardedpayton**
Command
```
vue config
```
 Now prints the resolved full path and content of ~/.vuerc

I'd like to get some feedback on this and make sure I'm in the right direction for implementing the rest of this feature.

### CODE REVIEW

**Comment by beardedpayton** [comment]
@Akryum hows this PR look ? Thanks

**Comment by yyx990803** [comment]
You're on the right path :)

**Comment by beardedpayton** [comment]
@yyx990803 awesome! You want to merge this PR and me continue to add the features?

**Comment by yyx990803** [comment]
Well we won't merge it until it actually implements what is outlined in the issue...

**Comment by beardedpayton** [comment]
@yyx990803 gotcha! I'll work on the rest :)

**Comment by beardedpayton** [comment]
@Akryum I get it on one of your commands as well locally

```vue ui port 5000```

Do you see that on your end? Or could this be something with my environment?

**Comment by beardedpayton** [comment]
I'll reopen a new one with all the additional features as soon as I hear back what you would like to do about ```vue config --set <path> <value>.

See latest here https://github.com/vuejs/vue-cli/issues/1506

**Pull request closed without merging**
