### PR TITLE
Add a demo for multiple loaders

### PR DESCRIPTION
**Pull request by FrankFang**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

**Comment by NataliaTepluhina** [comment]
Thank you for your contribution! Could you please change the target branch to `master`? According the [Contributing guide](https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#workflow), all documentation PRs should target either `master` or `next`, not `dev`

**Comment by FrankFang** [comment]
@NataliaTepluhina Ok, done.

**Comment by FrankFang** [comment]
@NataliaTepluhina It makes sense. Done.

**Comment by NataliaTepluhina** [comment]
@FrankFang thank you! Let's make it merged now 🎉

**Pull request merged**
