### PR TITLE
Update create project command

### PR DESCRIPTION
**Pull request by GauravJain98**

### CODE REVIEW

**Comment by hsxfjames** [comment]
The dev branch is for `@vue/cli` 3.0, and its create command is available. To see it:
```bash
npx @vue/cli create --help
```

And there is still `vue init webpack my-project` in master branch, which is for `vue-cli` 2.0. Are you seriously?

**Comment by GauravJain98** [comment]
It wasn't working on mine so I thought it was deprecated

**Comment by GauravJain98** [comment]
😅

**Comment by GauravJain98** [comment]
How can I delete this or now?

**Pull request closed without merging**
