### PR TITLE
Refactor: consistent command structure

### PR DESCRIPTION
**Pull request by beardedpayton**
Makes the Vue command structure more consistent. Easier to read over what they are doing during development.

### CODE REVIEW

**Comment by pksunkara** [comment]
Could you rebase over the latest dev branch please? Code looks good though.

**Comment by beardedpayton** [comment]
@pksunkara closed this due to rebasing issue. I did a ```git pull --rebase upstream dev``` but for some reason commits already merged are still showing?

**Comment by pksunkara** [comment]
There's only 1 new commit here, right? Sometimes it's better to just reset the whole thing and add that commit.

**Comment by beardedpayton** [comment]
@pksunkara correct only one new commit. How would I go about resetting and just add that one commit? Thanks

**Comment by pksunkara** [comment]
Reset your local `dev` stage `git reset --hard upstream/dev` after doing `git fetch upstream`

**Comment by beardedpayton** [comment]
@pksunkara okay I did that. Just added two more commits to PR ?

**Comment by pksunkara** [comment]
1. Make sure your upstream is vuejs/vue-cli. Origin is beardedpython/vue-cli
2. Fetch it. `git fetch upstream`
3. `git checkout dev`
4. `git reset --hard upstream/dev`
5. Add the commit.
6. `git push --force origin dev`

**Comment by pksunkara** [comment]
`git reset --hard` means the local branch will set to that branch. Which means any commit you made before will vanish. So, you have to add it back again. And `--force` in `git push` is the important part. Let's discuss in discord if you are still having issues. My username is the same there.

**Pull request closed without merging**
