### PR TITLE
docs: remove old note indicating the Nightwatch version

### PR DESCRIPTION
**Pull request by beatfactor**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

**Comment by beatfactor** [comment]
@NataliaTepluhina actually I see that in master nightwatch version is still v0.9. Do you think it might be time for an upgrade? I can follow up with that and also fix the config as well.

**Comment by NataliaTepluhina** [comment]
@sodatea what do you think about upgrading Nightwatch?

**Comment by sodatea** [comment]
We've upgraded nightwatch version in v4. So maybe only remove the note in the `next` branch?

**Comment by beatfactor** [comment]
In the meantime we have released a v1.2 version. I would also like to submit some improvements on the default configuration and maybe some more test examples in the template (to include more advanced topics like page objects, several more custom commands, and instructions on how to write those). 

We can remove the Selenium server, or at least offer standalone support for Chromedriver and Geckodriver by default. You can have a look at our example project [here](https://github.com/nightwatchjs/nightwatch-website-tests) - ideally the Vue plugin would be more in sync with this. It would also help us to get more input on how Nightwatch is being used as part of Vue.

What would be the appropriate branch where to send these improvements?

**Comment by sodatea** [comment]
The latest code lives in the `dev` branch.

**Pull request closed without merging**
