### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by ivansieder**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

**Comment by ivansieder** [comment]
done, thank you!

**Comment by sodatea** [comment]
Seems no commits were pushed? 😅

**Comment by ivansieder** [comment]
Uhm, looks like instead of adding a commit here, I created a new PR #5667, might that still work? 😂

**Comment by sodatea** [comment]
Yeah that's ok, too.

**Pull request merged**
