### PR TITLE
Make prompts when support function.

### PR DESCRIPTION
**Pull request by likun7981**
Now  we only set prompts __when__ is an attribute from the other prompts , and the prompt must be a  boolean . but sometimes we want set the __when__ to a special value,  when a prompt choice the value , we return a boolean.  
so I resolve this problem; I through this example to illustrate;

previously , we can only set prompt like this
```js
q1: {
  type: 'confirm',
  require: true,
  message: 'this is a question?',
  default: true
},
q2: {
  when: 'q1',
  type: 'list',
  message: 'Which choice ?',
  choices:[] // some choices
}
```
If __q1__ is not a _confirm_ , it is a _list_, like this 
```js
q1: {
  type: 'list',
  message: 'make choice?',
  choices:['c1','c2'] // some choices
},
q2: {
  when: ????,
  type: 'list',
  message: 'Which choice ?',
  choices:[] // some choices
}
```
now  we want to when __q1__ choice _c1_ , then ask __q2__, otherwise do not ask __q2__;

so  when  should like __inquirer__ to support set _function_ value to __when__

we can set like this:
```js
q1: {
  type: 'list',
  message: 'make choice?',
  choices:['c1','c2'] // some choices
},
q2: {
  when: function(answers){
    return answers.q1 === 'c1';
  },
  type: 'list',
  message: 'Which choice ?',
  choices:[] // some choices
}
```

### CODE REVIEW

**Comment by posva** [comment]
Can you add a test for this, please? 🙂

**Comment by likun7981** [comment]
The test is ok

**Comment by posva** [comment]
ping @egoist @zigomir

**Comment by zigomir** [comment]
Looks good to me! I only maybe miss a test case that exercises previous `when` functionality. I know this is not a concern for this PR, but it might be useful to prevent any regressions.

**Comment by likun7981** [comment]
No one to deal with this PR ?  😳

**Comment by yyx990803** [comment]
Thanks for the PR and sorry for letting it sit for so long. As of now, we are no longer adding new features of vue-cli 2.x, so I am closing this PR. Again, thanks for the contribution.

**Pull request closed without merging**
