### PR TITLE
Multi choice.

### LINKED ISSUE #5: multiple choice prompts
I would like create a vue-cli template  that prompts  users to select which libraries (js libraries, css preprocessor, etc) to install. Here's a screenshot from a yeoman generator that lets users pick one css preprocessor and multiple angular libraries.

screen shot 2015-12-29 at 8 36 47 pm
screen shot 2015-12-30 at 6 35 36 am

 Is it possible to have multiple choice prompts using  vue-cli?

### PR DESCRIPTION
**Pull request by zigomir**
Fixes #5. 

Example `meta.json`

```json
{
  "schema": {
    "name": {
      "type": "string",
      "required": true,
      "label": "Project name"
    },
    "description": {
      "type": "string",
      "required": true,
      "label": "Project description",
      "default": "A Vue.js project"
    },
    "author": {
      "type": "string",
      "label": "Author"
    },
    "private": {
      "type": "boolean",
      "default": true
    },
    "preprocessor": {
      "label": "CSS Preprocessor",
      "type": "checkbox",
      "choices": [
        "less",
        "sass"
      ]
    }
  }
}
```

example `package.json`

```json
{
  "name": "{{ name }}",
  "description": "{{ description }}",
  "author": "{{ author }}",
  {{#private}}
  "private": true,
  {{/private}}
  "scripts": {
    "watchify": "watchify -vd -p browserify-hmr -e src/main.js -o dist/build.js",
    "serve": "http-server -c 1 -a localhost",
    "dev": "npm-run-all --parallel watchify serve",
    "build": "cross-env NODE_ENV=production browserify src/main.js | uglifyjs -c warnings=false -m > dist/build.js"
  },
  "dependencies": {
    "vue": "^1.0.0"
  },
  "devDependencies": {
    {{#preprocessor.less}}
    "less": "^2.6.1",
    {{/preprocessor.less}}
    {{#preprocessor.sass}}
    "node-sass": "^3.4.2",
    {{/preprocessor.sass}}
    "babel-core": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "babel-runtime": "^5.8.0",
    "cross-env": "^1.0.6",
    "babelify": "^7.2.0",
    "browserify": "^12.0.1",
    "browserify-hmr": "^0.3.1",
    "http-server": "^0.9.0",
    "npm-run-all": "^1.6.0",
    "uglify-js": "^2.5.0",
    "vue-hot-reload-api": "^1.2.2",
    "vueify": "^8.0.0",
    "vueify-insert-css": "^1.0.0",
    "watchify": "^3.4.0"
  },
  "browserify": {
    "transform": [
      "vueify",
      "babelify"
    ]
  }
}
```

It would probably make sense to document this feature a bit more in readme.

### CODE REVIEW

**Comment by yyx990803** [comment]
Sweet!, thanks a lot!

**Comment by yyx990803** [comment]
@zigomir btw, really appreciate your contributions - interested in joining the vuejs team? I can add you as a maintainer of vue-cli. We also have a slack for collaborators :)

**Comment by zigomir** [comment]
Yes, totally. I'd love to do that. I also wanted to start working on tests
as next thing that vue-cli needs. I see we already have an issue for that
:) Where can I join slack?

**Comment by yyx990803** [comment]
Awesome, just sent you invite.

**Pull request merged**
