### PR TITLE
fix(cli-plugin-eslint): make eslint deps optional

### PR DESCRIPTION
**Pull request by sodatea**
1. In @vue/cli-plugin-eslint 3.1.0+, eslint will be explicitly added to
the project's package.json, so it is **optional**.
2. `optionalDependencies` will still be installed by npm by default,
just no longer cause installation to fail when error happens.
3. ESLint v4 did cause weird errors sometimes, like `npm WARN
ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed.`
Though this warning never caused any errors on my machine, I think it's
good to make the plugin fail-safe.

This change fixes https://github.com/vuejs/vue-cli/issues/3009

### CODE REVIEW

**Comment by sodatea** [comment]
This should also fix https://github.com/vuejs/vue-cli/issues/2567#issuecomment-443641175

**Comment by sodatea** [comment]
Note: This may break use cases like this if their projects were created by @vue/cli v3.0.x: https://github.com/vuejs/vue-cli/issues/1242#issuecomment-423000452

**Comment by one-pieces** [comment]
This update will break the projects were created by @vue/cli v3.0.x

**Comment by sodatea** [comment]
@one-pieces Did you run `npm install` with `--no-optional`? I didn't expect that use case to exist… 😂

**Pull request merged**
