### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mlars84**
Just a small grammar catch.

### CODE REVIEW

**Comment by Akryum** [comment]
This is not a typo. 😸

**Comment by mlars84** [comment]
Doesn't `CLI Service` possess `detailed usage` aka `The section on CLI Service covers it's detailed usage.`

**Comment by Akryum** [comment]
You are basically writing `The section on CLI Service covers it is detailed usage.`

**Comment by mlars84** [comment]
I see now. Right you guys are! My bad.

**Pull request closed without merging**
