### PR TITLE
feat(cli-service): add "VUE_CLI_SERVICE_PARAMS"

### PR DESCRIPTION
**Pull request by zyao89**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Docs
- [ ] Code style update
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

**Comment by sodatea** [comment]
What's the use case?

**Comment by zyao89** [comment]
i want to preload some plugins. doesn't only depend on pkg.

eg: 
```js
// ./params.js
module.exports = {
    useBuiltIn: true,
    plugins: [
        ...
    ],
};
```
or
```js
// ./params.js
module.exports = function(){
    return {
        useBuiltIn: true,
        plugins: [
            ...
        ],
    };
}
```

```js
process.env.VUE_CLI_SERVICE_PARAMS = './params.js'
```

> What's the use case?

**Comment by sodatea** [comment]
> doesn't only depend on pkg

Why? Why don't you want it to depend on pkg? Any technical obstacles or personal taste?

**Comment by zyao89** [comment]
just want more choices. 

eg:  custom cli.
```js
module.exports = () => {
    const PRI_DEPS = [ ... ]; // preload
    return {
        useBuiltIn: true,
        pkg,
        plugins: PRI_DEPS.map(id => {
            return {
                id,
                apply: require(id),
            };
        }).concat(projectPlugins),
    };
}
```

> > doesn't only depend on pkg
> 
> Why? Why don't you want it to depend on pkg? Any technical obstacles or personal taste?

**Comment by sodatea** [comment]
> just want more choices.

It's not how we add features. We need a convincing use case. We don't want to increase the maintenance burden unless for good reasons.

> eg: custom cli.

Then why modify the Vue CLI source? You can write your own CLI on top of the Vue CLI API, by requiring `@vue/cli-service/lib/Service` in your own package.

**Comment by zyao89** [comment]
@sodatea thanks! I will close this, but I make a new PR(#5311) to solve it.

**Pull request closed without merging**
