### PR TITLE
Fixed update info's formatting.

### PR DESCRIPTION
**Pull request by RatanShreshtha**
Before the prompt for new available update looked like this

┌─────────────────┐
│ ✨  Update available: 3.0.0-alpha.13 ✨  │
└─────────────────┘

After 

┌──────────────────┐
│ ✨  Update available: 3.0.0-alpha.13 ✨  │
└──────────────────┘

### CODE REVIEW

**Comment by yyx990803** [comment]
What OS / shell / terminal are you using? It looks fine in macOS/bash...

**Comment by RatanShreshtha** [comment]
I am using fish on fedora 27.

**Comment by RatanShreshtha** [comment]
Can anyone tell me how can I test this and make sure that it's not a shell / terminal issue.

**Comment by chrisvfritz** [comment]
@RatanShreshtha Emoji can sometimes do strange things with length counts, such as:

``` js
'🙏🏻'.length //=> 4
```

In the above scenario, it's because the emoji is actually a ligature. I wonder if something similar is happening, like maybe `✨` isn't fully supported on the system so not included in the length? Total stab in the dark, but you could try `'✨'.length` to see what you get.

**Comment by yyx990803** [comment]
Or we can just remove the emoji to avoid the headache ;)

**Comment by RatanShreshtha** [comment]
I have tried `'✨'.length` in node repel and its giving me `1` as the output.

**Comment by chrisvfritz** [comment]
Hm, would you mind trying to remove the emoji locally anyway and seeing if that fixes it?

**Pull request closed without merging**
