### PR TITLE
vue-cli UI

### PR DESCRIPTION
**Pull request by Akryum**
*Initial release may not include all items in this list.*

**Main components:**
- [x] Project creation
  - [x] Preset save
  - [ ] Remote preset
  - [ ] Preset management
- [x] Project import
- [x] Project list
  - [x] Remove project
  - [x] Favorite project
- [x] Project plugins
  - [x] View installed plugins with some details
  - [x] Search (thanks to Algolia) and add a new plugin
  - [x] Plugin updates
  - [x] Git Diff
- [x] Project configuration
  - [x] JSON files
  - [x] Embedded in package.json
  - [x] YAML files
  - [x] JS files
- [x] Project tasks
  - [x] Parameters
  - [x] Webpack Dashboard view
  - [x] Bundle visualizer view
- [x] cli-ui plugins system
  - [x] 3rd-party component loading
  - [x] Realtime SharedData
  - [x] PluginAction
  - [x] IPC

**Secondary components:**
- [x] Folder explorer
  - [x] Green icon for folders with `package.json` file
  - [x] Vue icon for vue-cli 3.x projects
  - [x] Favorite folders
- [x] Prompts system
  - [x] list/rawlist
  - [x] confirm
  - [x] checkbox
  - [x] input/password
  - [ ] expand
  - [ ] editor
  - [x] color
- [x] Status bar
  - [x] Current project
  - [x] CWD
  - [x] vue-cli logs
  - [x] Bug report button
  - [ ] Plugin support
- [x] Project nav
  - [x] Badges (running tasks, plugin updates)
  - [x] Plugin support
- [x] Git Diff GUI
  - [x] Show file diff
  - [x] Commit
  - [x] Open file
- [x] Desktop notifications

**Other:**
- [x] Localization #987 
- [x] Built and runnable distribution

### CODE REVIEW

**Comment by anteriovieira** [comment]
@Akryum could implement the same interface as devtools, what do you think?

**Comment by igeligel** [comment]
Looks nice 👍 

Have optimized images so package keeps a little bit smaller. Everything was optimized with [tinypng](https://tinypng.com/). You can find the imgur album [here](https://imgur.com/a/tkmn9).

Here are the direct links to the optimized images:

- babel: https://i.imgur.com/Q2njgfp.png
- eslint: https://i.imgur.com/T1GMyek.png
- pwa: https://i.imgur.com/R94sIco.png
- typescript: https://i.imgur.com/xyJuHEF.png
- jest: https://i.imgur.com/4AzqLky.png
- mocha: https://i.imgur.com/15S6Mfr.png
- nightwatch: https://i.imgur.com/0NNio3H.png
- cypress: https://i.imgur.com/S30LOJy.png
- vue logo: https://i.imgur.com/ak48f6u.png

Would be nice if we can replace some logos with svgs i guess. Can do some work on the weekend if you want. Just ping me 👍

**Comment by Akryum** [comment]
@igeligel You can do a PR to this branch. 😉

**Comment by Akryum** [comment]
@anteriovieira You mean embeding the devtools into cli-ui?

**Comment by anteriovieira** [comment]
Sorry for my english, I meant use the same layout.

**Comment by leovanhaaren** [comment]
@Akryum is there a way to get this running locally? I'm interested in how it looks & works and would love to check it out somehow.

**Comment by Akryum** [comment]
@leovanhaaren You can clone the feat-ui branch, yarn in the root then follow the readmes of `packages/@vue/cli-ui` and `packages/@vue/cli-ui-addon-webpack`.

**Pull request merged**
