### PR TITLE
feat: enhance error message when plugin module isn't loaded correctly

### PR DESCRIPTION
**Pull request by beardedpayton**
Fix for #4024

@sodatea Let me know if it makes more sense to implement this change somewhere else in the codebase.

### CODE REVIEW

**Comment by sodatea** [comment]
Thanks for this PR! But the error actually comes from here:
https://github.com/vuejs/vue-cli/blob/80e5d7ff36231fc31d2ed89fcf8f90483dbb3bec/packages/%40vue/cli/lib/add.js#L51-L55

For normal plugins, we do have proper error handling:
https://github.com/vuejs/vue-cli/blob/80e5d7ff36231fc31d2ed89fcf8f90483dbb3bec/packages/%40vue/cli/lib/invoke.js#L72-L83

So once [this issue](https://github.com/vuejs/vue-cli/issues/2335) is resolved and vuex & vue-router become standalone plugins, the error message will be correctly displayed. I think @pksunkara is currently working on this.

**Comment by pksunkara** [comment]
I just implemented the first part of it, PR #4196

**Comment by beardedpayton** [comment]
@sodatea ahh makes sense now. This sounds like a more permanent fix. Is there a way I can get in touch to find out what issues to work on? I plan on dedicating some time to knock out some smaller issues. Thanks

**Comment by sodatea** [comment]
@beardedpayton @pksunkara 

Just wrote up a [Status of Vue CLI](https://gist.github.com/sodatea/37bc8c36d7d0c285dfea52fbe8ddaf90)
Thanks for all your kind help 😀

**Pull request closed without merging**
