### PR TITLE
Catch version check error

### PR DESCRIPTION
**Pull request by Dmarch28**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

**Other information:**

### CODE REVIEW

**Comment by sodatea** [comment]
???
What's the purpose of this PR?

**Comment by Dmarch28** [comment]
SQL Server for Korea connections

**Comment by sodatea** [comment]
I don't understand.
These lines of code are already in the codebase, why did you resubmit them as a PR?

**Comment by Dmarch28** [comment]
Having problems with Microsoft Admin Center & Azure keep's bumping my info.
My signin was error-up, so resign in help my PR

**Comment by Dmarch28** [comment]
Also using visual studio code for container server

**Comment by sodatea** [comment]
Still no idea how's this PR related to the described problem. So I'm closing it.

**Comment by Dmarch28** [comment]
OK!!!

**Pull request closed without merging**
