### PR TITLE
chore(cli-plugin-eslint): Update packages

### PR DESCRIPTION
**Pull request by michalsnik**
This PR updates eslint-plugin-vue to the newest version, alongside ESLint

### CODE REVIEW

**Comment by sodatea** [comment]
FYI we have already updated eslint & eslint-plugin-vue version in the generator (https://github.com/vuejs/vue-cli/commit/7ccf7b37fa31fb80bd3137424a1be19577a2fb99) and updating the direct dependency would be a breaking change so this won't be merged until v4.

**Comment by michalsnik** [comment]
Thanks for the heads up! I see there is `^5.0.0-0` not `^5.0.0`. Won't it be a problem?

**Comment by sodatea** [comment]
🙂`^5.0.0-0` matches all 5.x versions including beta releases, that’s a temporary placeholder before 5.x stable release is available. It can be changed to `^5.0.0` now that 5.0.0 is officially out.

**Comment by DRoet** [comment]
So to be clear... If your project was created by cli `3.x` with the following structure:

```
  "devDependencies": {
    "@vue/cli-plugin-babel": "3.2.0",
    "@vue/cli-plugin-eslint": "3.2.1",
    "@vue/cli-service": "3.2.0",
    "@vue/eslint-config-standard": "4.0.0",
    "node-sass": "4.11.0",
    "sass-loader": "7.1.0",
    "vue-template-compiler": "2.5.20"
  }
```

To be able to use eslint `^5.0.0` you would have to:

**A)** Wait for `"@vue/cli-plugin-eslint": "^4.0.0"` to get released

or 

**B)** manually add `eslint`, `babel-eslint` and `eslint-plugin-vue` to your `devDependencies` like the `3.1.x` generator does to overwrite the default

is this correct?

**Comment by sodatea** [comment]
@DRoet Yes that's correct.

**Pull request closed without merging**
