### PR TITLE
fix: make vue-loader-v16 an optional dependency, avoid crashing npm 5

### LINKED ISSUE #5715: verson 4.5.0 dosen't suport npm5.6.0
### Version
4.5.0

### Environment info
```
npm 5.6.0
node 8.11.3
```

### Steps to reproduce
in npm 5.6.0

execute `npm install` with @vue/cli-service v4.5.0 

get error:

error in npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:vue-loader@^16.0.0-beta.3

### What is expected?
npm install can be executed in npm5.6.0

### What is actually happening?
@vue/cli-service v4.5.0 dosen't support npm 5.6.0

---
Notice that package aliasing is support since npm 6.9.0

Will npm5.6.0 be supported again?

### PR DESCRIPTION
**Pull request by sodatea**
fixes #5715

*What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

**Comment by aa6my** [comment]
Hi,

Stuck at amplify installation

` Error: Cannot find module 'vue-loader-v16/package.json'`

p/s - using vue 3 & babel

**Comment by aa6my** [comment]
> Hi,
> 
> Stuck at amplify installation
> 
> ` Error: Cannot find module 'vue-loader-v16/package.json'`
> 
> p/s - using vue 3 & babel

temporary fixed `npm install "vue-loader-v16@npm:vue-loader@v16.0.0-alpha.3"`

**Comment by pranvatsa** [comment]
Still see the issue as mentioned by @aa6my . 

Steps to reproduce the issue 

1. node version 10.15.3  , npm version 6.4.1
2. npm install -g  @vue/cli 
3. vue create testProject
4. Choose Default (Vue 3 Preview) ([Vue 3] babel, eslint) 
5. cd testProject and run > npm run serve

Error logs - 
```
 INFO  Starting development server...
 ERROR  Error: Cannot find module 'vue-loader-v16/package.json'
 Error: Cannot find module 'vue-loader-v16/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
```

**Comment by justyeh** [comment]
> > Hi,
> > Stuck at amplify installation
> > ` Error: Cannot find module 'vue-loader-v16/package.json'`
> > p/s - using vue 3 & babel
> 
> temporary fixed `npm install "vue-loader-v16@npm:vue-loader@v16.0.0-alpha.3"`

I ran into the same problem, but the temporary method did not work

```
npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\54657645\AppData\Roaming\npm-cache\_logs\2020-08-17T07_15_51_509Z-debug.log
```

**Comment by sodatea** [comment]
Please use npm >= 6.9 and avoid adding the `--no-optional` flag.

**Comment by justyeh** [comment]
> Please use npm >= 6.9 and avoid adding the `--no-optional` flag.

Problem solved, thank you

**Comment by thetnaingtn** [comment]
I updated npm to 6.14.8 but still have problems.
Temporary fixed with npm install --save-dev vue-loader-v16.
can somebody give me any idea or help?
Thanks in advance

**Comment by doradsoft** [comment]
> Same problem here.
> I updated npm to 6.14.8 but still have problems.
> Temporary fixed with npm install --save-dev vue-loader-v16.
> can somebody give me any idea or help?
> Thanks in advance

Same here. @sodatea

**Pull request merged**
