### PR TITLE
feat: implement version-related APIs for `GeneratorAPI`

### PR DESCRIPTION
**Pull request by sodatea**
To discuss: is the name `serviceVersion` / `assertServiceVersion` ideal? Any other naming ideas?

### CODE REVIEW

**Comment by novbing** [comment]
> To discuss: is the name `serviceVersion` / `assertServiceVersion` ideal? Any other naming ideas?

`serviceVersion` / `exactServiceVersion`
`serviceVersion` / `lockedServiceVersion`
`serviceVersion` / `workServiceVersion`
...

**Comment by sodatea** [comment]
Well, I think the `assert` part is accurate. But is `serviceVersion` clear enough to indicate that it is actually a per-project version number, in contrast to the `version` field as a global version number?

**Comment by novbing** [comment]
currentVersion
localVersion
?

**Comment by sodatea** [comment]
`currentVersion` does not distinguish it from the global `version` field.

`localVersion` may be a good alternative but I'm not sure…
While `@vue/cli-service` is local, it is not depended on by `GeneratorAPI`…

**Comment by pksunkara** [comment]
I would name them as following:

* `cliVersion`
* `requireCliVersion`
* `cliServiceVersion`
* `requireCliServiceVersion`

IMO easier to understand what they mean

**Comment by sodatea** [comment]
🤔prefer `assert` because it's in line with `PluginAPI` and babel's API naming.

So,

- `cliVersion`
- `assertCliVersion`
- `cliServiceVersion`
- `assertCliServiceVersion`

WDYT?

**Comment by pksunkara** [comment]
Sounds good. We should probably backport this to v3 and let `assert*` just return `false`.

**Comment by sodatea** [comment]
Yeah, all non-breaking changes would be backported to v3.

**Pull request merged**
