### PR TITLE
refactor!: Switching from Request package to Got

### PR DESCRIPTION
**Pull request by jeneser**
BREAKING CHANGE: replace Request package with Got

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

**Other information:**

#5220

### CODE REVIEW

**Review by sodatea — CHANGES_REQUESTED** [review]
Thanks for the help! But please fix the failing tests. I think the refactored code is not working correctly.

**Comment by jeneser** [comment]
Oops! There is something wrong with the Yarn. I'm trying to fix it.

**Comment by sodatea** [comment]
Still failing.
I believe it's due to the usage of `.json()`

**Comment by jeneser** [comment]
I don't think so. All test suites are passed on my machine. But, AppVeyor build failed.

```
FAIL packages/@vue/cli-plugin-eslint/__tests__/eslintMigrator.spec.js
RequestError: connect ECONNREFUSED 127.0.0.1:443
```

It looks like `https-proxy-agent` or `agent-base` break `got` without even using it. Maybe we need downgrading to got@9, but it would be great to upgrade.

**Comment by jeneser** [comment]
```
> npm ls agent-base

/workspace/vue-cli
├─┬ chromedriver@84.0.1
│ └─┬ https-proxy-agent@5.0.0
│   └── agent-base@6.0.1 
├─┬ geckodriver@1.20.0
│ └─┬ https-proxy-agent@5.0.0
│   └── agent-base@6.0.1 
├─┬ lerna@3.22.1
│ └─┬ @lerna/add@3.21.0
│   └─┬ @evocateur/pacote@9.6.5
│     └─┬ make-fetch-happen@5.0.2
│       ├─┬ http-proxy-agent@2.1.0
│       │ └── agent-base@4.3.0 
│       └─┬ https-proxy-agent@2.2.4
│         └── agent-base@4.3.0  deduped
└─┬ lerna-changelog@1.0.1
  └─┬ make-fetch-happen@7.1.1
    ├─┬ http-proxy-agent@3.0.0
    │ └── agent-base@5.1.1 
    ├─┬ https-proxy-agent@4.0.0
    │ └── agent-base@5.1.1  deduped
    └─┬ socks-proxy-agent@4.0.2
      └── agent-base@4.2.1
```

`lerna` and `lerna-changelog` need the latest version. Specifically, `make-fetch-happen` and `agent-base` need the latest version.

**Comment by sodatea** [comment]
I now think we shouldn't use `got`. Now that it can be interfered with by other packages in the CLI repo, it might also be affected by other global packages installed on the user's machine. We need a safer replacement.

**Comment by jeneser** [comment]
You are right. The problem is not `got` fault. `agent-base` breaks `got`. But for now, so many packages need an upgrade to the latest version. Maybe that isn't such a great idea.

**Comment by jeneser** [comment]
Superseded by #6009

**Pull request closed without merging**
