### PR TITLE
fix: pnpm v7 install error

### PR DESCRIPTION
**Pull request by lvqq**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
pnpm v7 makes breaking change to set strict-peer-dependencies=true by default, which may cause problems when installing.

### CODE REVIEW

**Review by linghengqian — COMMENTED** [review]
You need to fix CI.

**Comment by linghengqian** [comment]
For https://github.com/vuejs/vue-cli/issues/6476 , https://github.com/vuejs/vue-cli/issues/7106 , https://github.com/vuejs/vue-cli/issues/7263 and https://github.com/vuejs/vue-cli/issues/7284.

**Comment by lvqq** [comment]
@linghengqian I will try it, but the error is not from my changes 😂

**Comment by lvqq** [comment]
@linghengqian I pass the test in my local environment and I don't find any similar error from tsPluginE2e. Is there someway to rerun the failed ci checker while not pushing some new changes? I can't find any rerun button here. Thanks!

Here is my local vs remote ci:
image

image

**Comment by linghengqian** [comment]
@lvqq 

- You can checkout to your local `fix-pnpm7-error` branch in the IDE, merge the `dev` branch, then push to your remote origin branch `fix-pnpm7-error`, and Github Action will restart.  For Jetbrains Webstorm, it can be operated directly in the graphical interface.

- I'm not sure why your fork local build succeeded, I haven't had time to start investigating this.

**Comment by lvqq** [comment]
@linghengqian, I have tried several times without any changes and get it passed finally. Besides, I get different check error every time. Maybe the check CI server is not very stable and it is a matter of luck 😂

**Comment by linghengqian** [comment]
CC @sodatea

**Review by linghengqian — APPROVED** [review]

**Comment by linghengqian** [comment]
Carbon Copy @wxsms @yyx990803 .

**Review by haoqunjiang — APPROVED** [review]

**Pull request merged**
