### PR TITLE
fix: NODE_ENV cannot be correctly set to "development"

### PR DESCRIPTION
**Pull request by cpg0525**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
When the environment is "dev", NODE_ENV cannot be correctly set to "development"

### CODE REVIEW

**Comment by fangbinwei** [comment]
Why check if NODE_ENV is'dev'?

**Comment by cpg0525** [comment]
> Why check if NODE_ENV is'dev'?

``

> Why check if NODE_ENV is'dev'?

Ensure that process.env.NODE_ENV is always development when the node environment is dev and config.get can read the development.json configuration correctly.

**Comment by cpg0525** [comment]
> Why check if NODE_ENV is'dev'?

Ensure that process.env.NODE_ENV is always development when the node environment is dev and config.get can read the development.json configuration correctly.Therefore, I think it is necessary to do an operation compatible with process.env.node _ env = development.

**Comment by sodatea** [comment]
Setting `NODE_ENV` to `'dev'` is not a good practice.
Doing an implicit conversion is not a good practice either.

Users would be extremely confused when debugging problems involving this conversion.

Better warn the user than silently convert the environment variable.

**Pull request closed without merging**
