### PR TITLE
docs(zh): change line to lines in plugin-dev.md

### PR DESCRIPTION
**Pull request by zhouxinyong**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
Fix code word writing errors, change line to lines.

### CODE REVIEW

**Comment by zhouxinyong** [comment]
ok, I change the branch to  master. @sodatea

**Comment by sodatea** [comment]
😅 Please don't bring unmerged commits from `dev` branch.

`dev` branch is used for development, so it might contain unreleased features and documentation for such features. `master` is used as a release branch, it only contains documentation for shipped features.

**Comment by sodatea** [comment]
I think you might need to rebase from master and force push the branch. Or you can open another PR…

**Comment by zhouxinyong** [comment]
ok, I will close this pr and send a new pr for this.

**Pull request closed without merging**
