### PR TITLE
docs: explain pwa head/manifest icons

### LINKED ISSUE #5407: PWA icon options are not clearly explained in docs
### What problem does this feature solve?
Per the conversation in [issues #4069](https://github.com/vuejs/vue-cli/issues/4069) and my own experience, the current documentation on icons for the PWA plugin does not clearly explain the difference between `pwa.iconPaths` and `pwa.manifestOptions.icons`.  In fact `pwa.manifestOptions.icons` isn't actually mentioned in the docs.

### What does the proposed API look like?
Simply adding a note to the `pwa.iconPaths` section explaining what these icon paths do and adding `pwa.manifestOptions.icons` to the `pwa.manifestOptions` section should solve most peoples confusion.

### PR DESCRIPTION
**Pull request by DRBragg**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

Closes #5407

### CODE REVIEW

**Comment by DRBragg** [comment]
I'm not really sure what's causing the AppVeyor failure.

**Comment by Alex-Sokolov** [comment]
It's removed in 4.4.0? https://github.com/vuejs/vue-cli/commit/6323b73260e461c4aeb866fde4231f15d19f9c4e#diff-122632498f7fe7afa2fc01595a67e13c

**Comment by sodatea** [comment]
That commit was generated by lerna. Really unexpected that it would ever change code other than the version numbers and changelog.

**Comment by SimonChaumet** [comment]
It was removed again ?

**Comment by sodatea** [comment]
Added back. Still confused 😕

**Comment by DRBragg** [comment]
🤷🏻 I can redo this PR on a fresh branch if that will help

**Comment by DRBragg** [comment]
Seems to be live now (finally 😂) 👍

**Comment by IsaacCespedes** [comment]
I am trying to see the new icon for my homescreen app and it does not change unless I reinstall. Am I missing something? Thank you.

This is my vue.config:
pwa: {
name: "MyApp",
themeColor: "#000000",
msTileColor: "#000000",
appleMobileWebAppCapable: "yes",
appleMobileWebAppStatusBarStyle: "black",
assetsVersion: "1.2",
iconPaths: {
favicon32: "img/icons2/favicon-32x32.png",
favicon16: "img/icons2/favicon-16x16.png",
appleTouchIcon: "img/icons2/apple-touch-icon-152x152.png",
maskIcon: "img/icons2/safari-pinned-tab.svg",
msTileImage: "img/icons2/msapplication-icon-144x144.png",
},
manifestOptions: {
icons: [
{
src: "./img/icons2/android-chrome-192x192.png",
sizes: "192x192",
type: "image/png",
},
{
src: "./img/icons2/android-chrome-512x512.png",
sizes: "512x512",
type: "image/png",
},
{
src: "./img/icons2/android-chrome-maskable-192x192.png",
sizes: "192x192",
type: "image/png",
},
{
src: "./img/icons2/android-chrome-maskable-512x512.png",
sizes: "512x512",
type: "image/png",
},
{
src: "./img/icons2/apple-touch-icon-60x60.png",
sizes: "60x60",
type: "image/png",
},
{
src: "./img/icons2/apple-touch-icon-76x76.png",
sizes: "76x76",
type: "image/png",
},
{
src: "./img/icons2/apple-touch-icon-120x120.png",
sizes: "120x120",
type: "image/png",
},
{
src: "./img/icons2/apple-touch-icon-152x152.png",
sizes: "152x152",
type: "image/png",
},
{
src: "./img/icons2/apple-touch-icon-180x180.png",
sizes: "180x180",
type: "image/png",
},
{
src: "./img/icons2/apple-touch-icon.png",
sizes: "180x180",
type: "image/png",
},
{
src: "./img/icons2/msapplication-icon-144x144.png",
sizes: "144x144",
type: "image/png",
},
{
src: "./img/icons2/mstile-150x150.png",
sizes: "150x150",
type: "image/png",
},
],
},

**Pull request merged**
