### PR TITLE
Jest template: fix the name of the tested file 

### PR DESCRIPTION
**Pull request by dunglas**
Replace `Hello.vue` by `HelloWorld.vue`

### CODE REVIEW

**Comment by posva** [comment]
I think you did the same PR twice 😄

**Comment by dunglas** [comment]
Almost, I noticed later that there is the same "problem" for the Mocha template.

**Comment by posva** [comment]
I mean it appears to be the exact same change on the same file (mocha plugin)

**Comment by yyx990803** [comment]
This PR is changing the mocha plugin :)

I think you can just change both plugins in the same PR.

**Comment by dunglas** [comment]
Done

**Pull request merged**
