### PR TITLE
feat(ui): add --host option

### PR DESCRIPTION
**Pull request by ykzts**
```console
$ vue ui --host 0.0.0.0
🚀  Starting GUI...
🌠  Ready on http://localhost:8000
```

Currently `vue ui` can not connect from outside. This is because it is bound to localhost.

In this Pull Request, an option is added so that it can be changed to host other than localhost.

### CODE REVIEW

**Comment by ykzts** [comment]
Unfortunately, if graphql versions do not match, you get an error :cry:

**Comment by ykzts** [comment]
> Thanks for the PR! Could you remove the unrelated dependency changes from it please? Thanks!

done!

**Comment by ykzts** [comment]
rebased

**Comment by liugang** [comment]
It's best to change -h to -H, because `-h` is use for  `-h, --help         output usage information`

```
option('-h, --host <host>', 'Host used for the UI server (default: localhost)')
```

**Pull request merged**
