### PR TITLE
feat: update npm.taobao.org to npmmirror.com

### PR DESCRIPTION
**Pull request by Certseeds**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

**Other information:**

maybe some package dependent the "npm.taobao.org" in there codes.

### CODE REVIEW

**Review by sodatea — APPROVED** [review]
Thanks!

**Comment by yoyo837** [comment]
Excuse me! What is the difference between them? Just an alias?

**Comment by jsw3363** [comment]
@sodatea

**Comment by jsw3363** [comment]
@sodatea 

Excuse me. I'm so sorry if I can ask you a question here but, could I take contributing - 

It's difficult because of the low priority, can I take docs? The language is Korean

**Comment by jsw3363** [comment]
@sodatea

Excuse me. I'm so sorry if I can ask you a question here but, could I take contributing - contributing guide?

It's difficult because of the low priority, can I take docs? The language is Korean

**Comment by Certseeds** [comment]
> Excuse me! What is the difference between them? Just an alias?
`npm.taobao.org` will stop service in middle of 2022, the new domain is `npmmirror.com`

**Comment by yoyo837** [comment]
Is there any official information links?

**Comment by Certseeds** [comment]
> Is there any links to official information for reference?

1. [cnpm update's it's own tool's commit log](https://github.com/cnpm/cnpm/commit/b3cbdc9f16a874c8292f2b5d1ecb467aa1788743#diff-d5109920b34c2b2e141bd41232d8876432a17479c388e142d8a036bb7b36ea62)
2. [npm.taobao.org](npm.taobao.org) now will auto 301 to `npmmirror.com`
2. [an unoffical article](https://zhuanlan.zhihu.com/p/430580607)
PS: maybe `npmmirror` should publish it in their own blog

**Comment by yoyo837** [comment]
> > Is there any links to official information for reference?
> 
> 1. [cnpm update's it's own tool's commit log](https://github.com/cnpm/cnpm/commit/b3cbdc9f16a874c8292f2b5d1ecb467aa1788743#diff-d5109920b34c2b2e141bd41232d8876432a17479c388e142d8a036bb7b36ea62)
> 2. [npm.taobao.org](npm.taobao.org) now will auto 301 to `npmmirror.com`
> 3. [an unoffical article](https://zhuanlan.zhihu.com/p/430580607)
>    PS: maybe `npmmirror` should publish it in their own blog

Thanks for your reply.

**Pull request merged**
