### PR TITLE
feat(build/serve): export build/serve command and allow them to take config argument (chainable webpack config)

### PR DESCRIPTION
**Pull request by nklayman**
Solves #1551 by changing the build command to export itself. It can then be imported and ran with a custom config that will be used instead of `api.resolveChainableWebpackConfig()`. This allows plugins to modify the webpack config only if their build command is run, not for normal builds. 

Edit: Now does same process for the serve command.

### CODE REVIEW

**Comment by nklayman** [comment]
Make sure to hide whitespace changes in the diff viewer. Indentation is updated, so it looks like there are more changes.

**Comment by nklayman** [comment]
For some reason that I can not find, HMR is broken in these cases:

 - serve function is imported and called from a plugin
 - serve function is called using `service.run('serve')` (assuming service = `new Service(api.resolve('.'))`)

Yet it still works when:

 - serve function is imported and called from a plugin, but only if calling package is linked with `yarn link`
 - called with `vue-cli-service serve`

**Comment by nklayman** [comment]
Another method of implementing this feature would be to allow `service.run()` to take a 4th argument. That argument would be an array of arguments that will be passed to the command the service calls. This would likely fix the HMR issue (and other related ones) and make it easier to add this feature to other plugins. I can create a PR for this method if it is preferred.

**Comment by Akryum** [comment]
> Another method of implementing this feature would be to allow service.run() to take a 4th argument. 

Worth a try.

**Comment by nklayman** [comment]
@akryum I created a branch with service.run taking a 4th argument: https://github.com/nklayman/vue-cli/tree/service-run-4th-arg

**Comment by nklayman** [comment]
If that works I can create a PR for that instead.

**Comment by nklayman** [comment]
Closing as I found an alternative and lack of interest.

**Pull request closed without merging**
