### PR TITLE
Add --port argument to 'vue serve' command

### PR DESCRIPTION
**Pull request by bokub**
Thanks to webpack, this one line addition in `packages/@vue/cli/bin/vue.js` is sufficient and works perfectly ! 🎉 

image

### CODE REVIEW

**Comment by bokub** [comment]
Thanks for the review !
Do you know when the PR will be merged ?

**Comment by pravosleva** [comment]
`--port` option does not work.
```
node 10.16.3
yarn 1.17.3
@vue/cli@3.10.0
```
image

**Comment by pravosleva** [comment]
Or `vue-cli-service serve --port 3000`
image
...But not specified port will be used.

**Comment by pravosleva** [comment]
Could any body please help me? )

**Comment by bokub** [comment]
The correct syntax is `vue-cli-service serve --port 3000`

- Are you sure the port 3000 is not already used ?
- Are you sure your dependencies are up to date ?
- Can you try `npm i @vue/cli@4.0.0-beta.1` ?

Also, please don't spam with multiple messages, use the 'edit' button instead

**Comment by pravosleva** [comment]
1) tcp port 3000 was killed in `dev.sh` before start by `$ yarn --cwd ./frontend serve` (screen)
2) All deps installed: `$ rm -rf ./node_modules && yarn install` in `/frontend`
3) Ok. `@vue/cli@4.0.0-beta.1` installed globally. But not specified port will be used again.
image

**Comment by bokub** [comment]
There is a difference between @vue/cli, and @vue/cli-service : https://cli.vuejs.org/guide/#components-of-the-system

- Can you try `vue serve --port 3000` from your terminal ? (it will use @vue/cli that you installed globally)

- Can you install `@vue/cli-service@4.0.0-beta.1` in your project and try again ?

**Comment by pravosleva** [comment]
1) `$ vue serve --port 3000` from terminal:
image
2) `"@vue/cli-service": "4.0.0-beta.1"` added as devDep then `$ yarn serve`
image

**Comment by bokub** [comment]
Wait, why do you have this message in case 1?
Don't you have an entry file? 

vue serve is a command made for [fast prototyping](https://cli.vuejs.org/guide/prototyping.html)

**Comment by pravosleva** [comment]
@bokub 
`/frontend` was created by `$ vue create frontend` as project with base files pack. In settings i selected `yarn` to use. So project could be started by `$ yarn serve`. Is not it so?

**Comment by duongle-kdnd** [comment]
I tried to specify port 8080 but it does not work. It always use random port. I took many time to try all ways that i can, but not. Anybody help me to solve this problem.
I wonder why don't Vue-cli use 8080 is default port, and the port number can be changed if anyone need.

**Comment by bokub** [comment]
OK I think I get it.

You're using the command `vue-cli-service serve`, and this thread is about `vue serve`, which is completely different.

 `vue-cli-service serve` runs the standard web server with HMR. [Doc here](https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-serve)

 `vue serve` is made for instant prototyping. [Doc here](https://cli.vuejs.org/guide/prototyping.html#instant-prototyping)

**Comment by bokub** [comment]
Conclusion: you're in the wrong thread, and maybe you should create a new issue

**Comment by pravosleva** [comment]
@bokub 
Do you think this issue could be closed successfully? ))

**Comment by bokub** [comment]
> @bokub
> Do you think this issue could be closed successfully? ))

This is not an issue but a Pull Request ! It's about a new feature I've added, not a problem encountered

**Comment by bokub** [comment]
Apparently, someone has the same problem as you 😉 
https://github.com/vuejs/vue-cli/issues/4452

**Comment by duongle-kdnd** [comment]
@bokub  As i comment above, can you help me. Why isn't -- port 8080 working to me.

**Comment by pravosleva** [comment]
This feature does not work. Unfortunately.
image

**Comment by bokub** [comment]
@pravosleva : Again, my feature has been added to the package `@vue/cli`, which is used by using the `vue` command (e.g `vue serve`).

You both have issues on the `vue-cli-service` command, which is related to the `@vue/cli-service` package, which is different from the first one.

**Comment by bokub** [comment]
@duongle-kdnd Can you give any details ?

**Comment by fchangjun** [comment]
The port setting is not in effect because a plug-in that scans for valid ports has recently been updated，
port
So the generated port is not the port we set. You can comment out the scanned code

**Comment by fchangjun** [comment]
This plug-in was updated yesterday, so it should be the newly built project that caused this problem.
portfinder

**Pull request merged**
