### PR TITLE
DOCS: Starting portuguese translation

### PR DESCRIPTION
**Pull request by hericlesme**

### CODE REVIEW

**Comment by yyx990803** [comment]
Hi @hericlesme , thanks for your translation. Before you put more work into this, we'd like to confirm that you are committed to keep the translation up-to-date for the long run. In the past, we've had translations falling out of date with the English branch as we update the docs very often, and that can cause confusions for users. This means you will need to be consistently watching for changes in the English docs and updating the translation in the future. Do you think you can do that?

**Comment by hericlesme** [comment]
Yes, I'll be watching the repository, especially commits related to docs.

**Comment by hericlesme** [comment]
I just started the translation now in an attempt to help both you and the vue-cli users. I know it's a long walk, but I plan to finish it, and update it.

**Comment by hericlesme** [comment]
@yyx990803 I'm just waiting for your approval to continue.

**Pull request closed without merging**
