### PR TITLE
Better handling of `publicPath: 'auto'`

### PR DESCRIPTION
**Pull request by AndreiSoroka**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

For module-federation need to use output auto
```javascript
const { defineConfig } = require('@vue/cli-service')
const webpack = require('webpack')

module.exports = defineConfig({
  configureWebpack: {
    output: {
      publicPath: 'auto', // <- ERROR: Avoid modifying webpack output.publicPath directly. Use the "publicPath" option instead.
    },
    optimization: {
      splitChunks: false,
    },
    plugins: [
      new webpack.container.ModuleFederationPlugin({
        name: 'vue_cli_demo',
        filename: 'remoteEntry.js',
        exposes: {
          './HelloWorld.vue': './src/components/HelloWorld.vue',
        },
        shared: {
          vue: {
            singleton: true,
          },
        },
      }),
    ],
  },
  transpileDependencies: true
})
```

Fix problem for
- https://github.com/module-federation/module-federation-examples/issues/307
- https://github.com/vuejs/vue-cli/issues/6823

after that I'll add example here
- https://github.com/module-federation/module-federation-examples/issues/1632

### CODE REVIEW

**Comment by hansonfang** [comment]
https://next.cli.vuejs.org/config/#publicpath VueConfig has option for this.

**Comment by AndreiSoroka** [comment]
@hansonfang 
image
Local:   http://localhost:8082/auto 

But... I'm checking at the moment, seems MF is working...

Last time it confused me and I went looking for a workaround

**Comment by AndreiSoroka** [comment]
@hansonfang updated MR

**Comment by AndreiSoroka** [comment]
@hansonfang what do you think about current Mr? (after update)

**Comment by AndreiSoroka** [comment]
FYI: @sodatea ?

**Comment by hansonfang** [comment]
@AndreiSoroka sorry I'm not member of contributor group. Maybe ask others to determine.

**Review by haoqunjiang — CHANGES_REQUESTED** [review]
Thanks for the PR.
But I think there are still many places that we need to fix for `publicPath: 'auto'` to work correctly.

For example, `process.env.BASE_URL` should be set to `''` in this case. So does the `baseUrl` argument for `genHistoryApiFallbackRewrites`.

After applying those changes, I think it would be more consistent to replace the `options.publicPath` here with `process.env.BASE_URL`, too.

**Comment by AndreiSoroka** [comment]
thanks. I will update mr on this week

**Comment by AndreiSoroka** [comment]
@sodatea done

**Comment by AndreiSoroka** [comment]
@sodatea Hi, can you re-review the code?

**Review by haoqunjiang — APPROVED** [review]

**Pull request merged**
