### PR TITLE
Added GraphQL Loader

### PR DESCRIPTION
**Pull request by BlackMix**
:)

### CODE REVIEW

**Comment by egoist** [comment]
hmm well there's even `.pug` support in the default config, I think it's ok to add `.gql` support since it's used a lot and doesn't introduce any dependencies.

**Comment by yyx990803** [comment]
Hmm yeah I don't think it should be in core.

**Comment by Akryum** [comment]
@egoist pug support is included for the `.vue` files.

**Comment by egoist** [comment]
@Akryum I mean the dependency is not included in `vue-cli` 😄

**Comment by Akryum** [comment]
But not in cli-service either so it won't work without another step from the user.

**Pull request closed without merging**
