### PR TITLE
Update version of eslint-loader

### PR DESCRIPTION
**Pull request by Amndeep7**
Update version of eslint-loader to the most recent release so as to be able to use the most recent release of eslint.  See #5698

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

**Other information:**
Will no longer support versions of eslint below 5.x.

### CODE REVIEW

**Comment by sodatea** [comment]
I'm sorry but we are only able to update to eslint-loader v3 in this major, due to breaking changes.

**Comment by Amndeep7** [comment]
3.0.4 of eslint-loader only supports the 5.x and 6.x branches of eslint.  This is still a change from the behavior for the version of eslint-loader currently being used (2.2.1) which is 1.6 through the 6.x branches of eslint.  What's the difference between dropping support for the 1.6-4.x branches of eslint and dropping support for the 1.6-5.x branches of eslint in terms of being a breaking change?

**Comment by sodatea** [comment]
Oh sorry, I thought we've already dropped ESLint v4 support. I just double-checked and it's still supported. Then we can't update the loader to either version.

**Comment by Amndeep7** [comment]
Thanks for the clarification @sodatea.  Is there any expectation for when the next major version update will be happening for this library?

**Pull request closed without merging**
