### PR TITLE
fix: add `sourceType: 'unambiguous'` to babel preset

### LINKED ISSUE #4773: @vue/cli 4.0.5 transpileDependencies invalid
### Version
4.0.5

### Reproduction link
[https://github.com/lxfu/vue-g6](https://github.com/lxfu/vue-g6)

### Environment info
```
Mac、IE11
```

### Steps to reproduce
npm i
npm run serve

### What is expected?
app should work  under IE11.

### What is actually happening?
The arrow function inside the dependency is not compiled

---
IE11 does not support arrow functions

### PR DESCRIPTION
**Pull request by sodatea**
Fixes #4773
The reasoning is stated at https://github.com/vuejs/vue-cli/issues/4773#issuecomment-548241889

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

### CODE REVIEW

**Comment by viniciuskneves** [comment]
I was migrating to Vue CLI 4 manually and I think this option is not documented here: https://github.com/vuejs/vue-cli/tree/v4.2.3/packages/@vue/babel-preset-app

Am I looking at the right place or is it documented somewhere else?

**Comment by sodatea** [comment]
It's a babel option: https://babeljs.io/docs/en/options#sourcetype

This PR only changes its default value to better handle edge cases. It doesn't affect actual usage.

**Comment by viniciuskneves** [comment]
> It's a babel option: https://babeljs.io/docs/en/options#sourcetype
> 
> This PR only changes its default value to better handle edge cases. It doesn't affect actual usage.

Yep, but from @LinusBorg https://github.com/vuejs/vue-cli/issues/4773#issuecomment-548259120 I thought it would be added to the docs (as a reference).

Just to be clear that it is not blocking me or anything. It is just because I was reading this PR + Issue mentioned and then doubled checked the docs.

I was using `unambiguous` in my project and could remove it after upgrading my dependencies as suggested.

**Comment by sodatea** [comment]
Yeah, you are right, we do need to add it in the docs.

**Comment by sodatea** [comment]
PR's welcome :)

**Pull request merged**
