### PR TITLE
fix: allow user to define testMatch in package.json (#1067)

### PR DESCRIPTION
**Pull request by dhensche**

### CODE REVIEW

**Comment by sylvainar** [comment]
Waiting for it to be merged, nice work!

**Comment by dhensche** [comment]
@laander with this additional commit it will respect options in either location

**Comment by dhensche** [comment]
What is the suggested change for when the tests only fail on CI because of timeouts? just increase the timeouts of the failing tests?

**Comment by Ldoppea** [comment]
You should try to push the commit again, the tests are failing on code not-related to your changes and it seems to pass on other merge requests.

Maybe @yyx990803 can help?

**Comment by posva** [comment]
I relaunched tests

**Comment by belaad** [comment]
a readme edit would have been great. How do I set the testmatch in package.json?

**Pull request merged**
