### PR TITLE
Add validation for package name in vue init	

### PR DESCRIPTION
**Pull request by watilde**
Hi :wave: 

I try to add a `validation` to check package name is [invalid or not](https://docs.npmjs.com/files/package.json#name) in `vue init`.
screenschot

### CODE REVIEW

**Comment by zigomir** [comment]
@watilde it would be really nice if you can also provide a test case.
I'm also a bit confused by the image you attached. Why is `Project name (test)` (guessing here the `test` is a project name) not valid?

**Comment by watilde** [comment]
@zigomir Thanks for your comment! I've rebased and added a test case.
I'm sorry for making you confused by a screenshot I attached. Actually this gif image is what exactly I did in the screenshot. Animation can explain it clearly :smiley: 
gif

**Comment by zigomir** [comment]
@watilde nice! Thanks for the update. This looks good to me. @yyx990803 do you agree as well?

**Comment by watilde** [comment]
@yyx990803 @zigomir Thanks!

**Pull request merged**
